run:
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  include:
    - EXC0002

# run `golangci-lint help linters` to find out more about each available linter.
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - exportloopref
    - goconst
    # TODO: enable after fixing lint errors
    #- gocritic
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
linters-settings:
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8
